version: '3.7'
services:
    db:
        image: 'mariadb:10.6.3'
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        volumes:
            - /Users/Alexandre/.data/mariadb-10.6.3-autograph:/var/lib/mysql
        ports:
            - '3306:3306'

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        environment: 
            ADMINER_DESIGN: dracula
            ADMINER_DEFAULT_SERVER: db
        depends_on: 
            - db
        ports:
            - '9000:8080'